[server]
name = "resume_generate_server"
port = 8000

[db]
url = "http://localhost:6333"

[llm]
model_url = "http://localhost:8080/v1"
model = "Llama-3-8B"
embedding_model_url = "http://localhost:8080/v1"
embedding_model = "Llama-3-8B"